User's Guide
------------

This part of the documentation begins with some background information about lms4labs, 
a step-by-step instructions for deploying it, and additional notes on how to add more 
RLMSs to it.

.. toctree::
   :maxdepth: 2

   foreword
   vocabulary
   design
   installation
   usage_labmanager_admin
   usage_lms_admin
   usage_teacher
   quickstart

API Reference
-------------

If you're interested in adding a new LMS or a new RLMS, you'll find a reference here.

.. toctree::
   :maxdepth: 2

   development
   lms_api
   rlms_api

