standard_urn_admin_roles:
        - Administrator
        - SysAdmin
        - AccountAdmin

permission_status:
        - pending
        - granted
        - denied

authentication_types:
        - oauth1.0
        - basic

user_access_level:
        - admin
        - rlms
        - lms

# 
# XXX 
# This should not be loaded from the YAML file,
# but from the registry (where extensions are loaded
# at the beginning)
# 
installed_rlms:
        WebLab-Deusto:
                - 5.0
        FCEIA-UNR:
                - 1.0
